### ISSUE TITLE
Meeting point

### ISSUE THREAD

**Issue by gortazar** [carlosyaen/jenkins-infrastructure-monitoring#1]
Si ves este issue es que estamos en el mismo barco :) Contesta para saber que has llegado hasta aquí.

**Comment by carlosyaen** [comment]
Listo!

**Comment by gortazar** [comment]
Ok. Algunas cuestiones primero:
- ¿Estás familiarizado con git?
- ¿Entiendes o intuyes cómo funciona zube.io desde el punto de vista de la planificación del proyecto?

**Comment by carlosyaen** [comment]
Git lo tenía creado pero nunca lo he utilizado. En cuanto a zube creo que me puedo defender porque si no me equivoco es algo parecido a trello.

**Comment by gortazar** [comment]
Sí, se parece a trello. 

¿Tienes experiencia con Jenkins? ¿Sabes al menos qué es?

**Comment by carlosyaen** [comment]
No, aunque he estado buscando un poco de información al respecto pero no me queda muy claro, así que si me lo pudieras explicar te lo agradecería.

**Comment by gortazar** [comment]
Os voy a enviar información para que os vayáis poniendo al día en los próximos días en issues específicos.
